### ISSUE TITLE
使用最新版svgjs会整体错位

### ISSUE THREAD

**Issue by yjhatfdu** [synyi/annotation-tool#2]
使用最新版svgjs会整体错位，具体表现在所有的annotations会上移，每往下一行偏移越多

**Comment by grzhan** [comment]
今天晚上我看一下

**Comment by yjhatfdu** [comment]
很强！

**Comment by grzhan** [comment]
@yjhatfdu 新版本 `svgjs` 的位移函数 `dy`，其在文本元素上的行为与其他元素相比发生了不一致，似乎会少减去一个`bbox.y`。

我不知道这是个 bug 还是个 feature，很迷。

总之我先把`text.dy(value)`改成`text.y(text.y() + value)`这样的写法了

**Comment by yjhatfdu** [comment]
ok,可以给svgjs提issue 了吧？
