### ISSUE TITLE
英文单词换行时会被强制拆开

### ISSUE THREAD

**Issue by yjhatfdu** [synyi/annotation-tool#7]
英文单词换行时会被强制拆开，建议换到下一行或者超过单行字符限制延长

**Comment by grzhan** [comment]
相当于需要支持 `word-wrap` 的默认属性这样吗。
由于之前一直都是在中文病历上搞，这个确实要考虑一下。
这周应该会实现。

**Comment by grzhan** [comment]
在 0.4.33 版本已实现
